export const countryNameToCode = {
  'United States': 'USA',
  'United States of America': 'USA',
  'USA': 'USA',
  'US': 'USA',
  'United Kingdom': 'GBR',
  'UK': 'GBR',
  'Great Britain': 'GBR',
  'England': 'GBR',
  'Scotland': 'GBR',
  'Wales': 'GBR',
  'Northern Ireland': 'GBR',

  'France': 'FRA',
  'Germany': 'DEU',
  'West Germany': 'DEU',
  'East Germany': 'DEU',
  'Italy': 'ITA',
  'Spain': 'ESP',
  'Portugal': 'PRT',
  'Netherlands': 'NLD',
  'Belgium': 'BEL',
  'Switzerland': 'CHE',
  'Austria': 'AUT',
  'Sweden': 'SWE',
  'Norway': 'NOR',
  'Denmark': 'DNK',
  'Finland': 'FIN',
  'Iceland': 'ISL',
  'Ireland': 'IRL',
  'Poland': 'POL',
  'Czech Republic': 'CZE',
  'Czechoslovakia': 'CZE',
  'Slovakia': 'SVK',
  'Hungary': 'HUN',
  'Romania': 'ROU',
  'Bulgaria': 'BGR',
  'Greece': 'GRC',
  'Croatia': 'HRV',
  'Serbia': 'SRB',
  'Slovenia': 'SVN',
  'Bosnia and Herzegovina': 'BIH',
  'Montenegro': 'MNE',
  'North Macedonia': 'MKD',
  'Macedonia': 'MKD',
  'Albania': 'ALB',
  'Kosovo': 'XKX',
  'Ukraine': 'UKR',
  'Belarus': 'BLR',
  'Moldova': 'MDA',
  'Lithuania': 'LTU',
  'Latvia': 'LVA',
  'Estonia': 'EST',
  'Russia': 'RUS',
  'Russian Federation': 'RUS',
  'Soviet Union': 'RUS',
  'USSR': 'RUS',
  'Luxembourg': 'LUX',
  'Malta': 'MLT',
  'Cyprus': 'CYP',
  'Monaco': 'MCO',
  'Liechtenstein': 'LIE',
  'Andorra': 'AND',
  'San Marino': 'SMR',
  'Vatican City': 'VAT',

  'Japan': 'JPN',
  'China': 'CHN',
  'Hong Kong': 'HKG',
  'Taiwan': 'TWN',
  'South Korea': 'KOR',
  'Korea': 'KOR',
  'Republic of Korea': 'KOR',
  'North Korea': 'PRK',
  'India': 'IND',
  'Thailand': 'THA',
  'Vietnam': 'VNM',
  'Philippines': 'PHL',
  'Indonesia': 'IDN',
  'Malaysia': 'MYS',
  'Singapore': 'SGP',
  'Pakistan': 'PAK',
  'Bangladesh': 'BGD',
  'Sri Lanka': 'LKA',
  'Nepal': 'NPL',
  'Myanmar': 'MMR',
  'Burma': 'MMR',
  'Cambodia': 'KHM',
  'Laos': 'LAO',
  'Mongolia': 'MNG',
  'Kazakhstan': 'KAZ',
  'Uzbekistan': 'UZB',
  'Turkmenistan': 'TKM',
  'Kyrgyzstan': 'KGZ',
  'Tajikistan': 'TJK',
  'Afghanistan': 'AFG',

  'Israel': 'ISR',
  'Palestine': 'PSE',
  'Palestinian Territory': 'PSE',
  'Turkey': 'TUR',
  'Iran': 'IRN',
  'Iraq': 'IRQ',
  'Saudi Arabia': 'SAU',
  'United Arab Emirates': 'ARE',
  'UAE': 'ARE',
  'Qatar': 'QAT',
  'Kuwait': 'KWT',
  'Bahrain': 'BHR',
  'Oman': 'OMN',
  'Yemen': 'YEM',
  'Jordan': 'JOR',
  'Lebanon': 'LBN',
  'Syria': 'SYR',
  'Egypt': 'EGY',

  'South Africa': 'ZAF',
  'Nigeria': 'NGA',
  'Kenya': 'KEN',
  'Morocco': 'MAR',
  'Algeria': 'DZA',
  'Tunisia': 'TUN',
  'Libya': 'LBY',
  'Ghana': 'GHA',
  'Senegal': 'SEN',
  'Ethiopia': 'ETH',
  'Tanzania': 'TZA',
  'Uganda': 'UGA',
  'Zimbabwe': 'ZWE',
  'Botswana': 'BWA',
  'Namibia': 'NAM',
  'Mozambique': 'MOZ',
  'Angola': 'AGO',
  'Cameroon': 'CMR',
  'Ivory Coast': 'CIV',
  "Côte d'Ivoire": 'CIV',
  'Democratic Republic of the Congo': 'COD',
  'Congo': 'COG',
  'Rwanda': 'RWA',
  'Sudan': 'SDN',
  'Mali': 'MLI',
  'Burkina Faso': 'BFA',
  'Niger': 'NER',
  'Madagascar': 'MDG',
  'Mauritius': 'MUS',

  'Canada': 'CAN',
  'Mexico': 'MEX',
  'Brazil': 'BRA',
  'Argentina': 'ARG',
  'Chile': 'CHL',
  'Colombia': 'COL',
  'Peru': 'PER',
  'Venezuela': 'VEN',
  'Ecuador': 'ECU',
  'Bolivia': 'BOL',
  'Uruguay': 'URY',
  'Paraguay': 'PRY',
  'Cuba': 'CUB',
  'Dominican Republic': 'DOM',
  'Puerto Rico': 'PRI',
  'Jamaica': 'JAM',
  'Haiti': 'HTI',
  'Trinidad and Tobago': 'TTO',
  'Bahamas': 'BHS',
  'Barbados': 'BRB',
  'Guatemala': 'GTM',
  'Honduras': 'HND',
  'El Salvador': 'SLV',
  'Nicaragua': 'NIC',
  'Costa Rica': 'CRI',
  'Panama': 'PAN',
  'Belize': 'BLZ',

  'Australia': 'AUS',
  'New Zealand': 'NZL',
  'Fiji': 'FJI',
  'Papua New Guinea': 'PNG',

  'Federal Republic of Germany': 'DEU',

  'Republic of Ireland': 'IRL',
  'Republic of Korea': 'KOR',
  'Republic of China': 'TWN',
  'People\'s Republic of China': 'CHN',
};

export const codeToCountryName = Object.entries(countryNameToCode).reduce((acc, [name, code]) => {
  if (!acc[code] || name.length > acc[code].length) {
    acc[code] = name;
  }
  return acc;
}, {});

codeToCountryName['USA'] = 'United States';
codeToCountryName['GBR'] = 'United Kingdom';
codeToCountryName['RUS'] = 'Russia';
codeToCountryName['KOR'] = 'South Korea';
codeToCountryName['DEU'] = 'Germany';
codeToCountryName['NLD'] = 'Netherlands';

export function normalizeCountryName(name) {
  if (!name) return null;
  const trimmed = name.trim();
  return countryNameToCode[trimmed] || null;
}

export function getDisplayName(code) {
  return codeToCountryName[code] || code;
}
